### ISSUE TITLE
SIGABRT processing MIPS binary

### ISSUE THREAD

**Issue by wontonSlim** [Vector35/binaryninja-docs#141]
Binary Ninja 1.0.281/ Ubuntu 14.04 

I'd like to apologize about being unable to post my test case. Intellectual property problems.

Binary ninja will crash on processing certain MIPS binaries.

Stack trace of crashing thread:
```
#0  0x00007ffff5648cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff564c0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff5f53535 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5f516d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5f51703 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5fa4ad5 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff5195182 in start_thread (arg=0x7fffe2057700) at pthread_create.c:312
#7  0x00007ffff570c47d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```
Thread creation : libbinaryninjacore.so.1 + 0x5c994

Thread creation stack trace:
```
#0  __pthread_create_2_1 (newthread=0x7fffffffc0e0, attr=0x0, start_routine=0x7ffff5fa4a20, arg=0xf8a6b8) at pthread_create.c:466
#1  0x00007ffff5fa4c8f in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>) ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007ffff7a2a999 in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libbinaryninjacore.so.1
#3  0x00007ffff7a2aae2 in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libbinaryninjacore.so.1
#4  0x00007ffff7a2b37d in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libbinaryninjacore.so.1
#5  0x00007ffff7a44a03 in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libbinaryninjacore.so.1
#6  0x00007ffff7a3ea6d in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libbinaryninjacore.so.1
#7  0x00000000004360c9 in ViewFrame::ViewFrame(QWidget*, FileContext*, QString const&) ()
#8  0x0000000000429c1a in MainWindow::createTab(FileContext*, QString const&, bool) ()
#9  0x000000000042f0c7 in MainWindow::openFilename(QString const&) ()
#10 0x00007ffff64b735e in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Core.so.5
#11 0x00007ffff73e2b22 in QLabel::linkActivated(QString const&) () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#12 0x00007ffff73e57f1 in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#13 0x00007ffff64b735e in QMetaObject::activate(QObject*, int, int, void**) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Core.so.5
#14 0x00007ffff74677a5 in QWidgetTextControl::linkActivated(QString const&) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#15 0x00007ffff746cc9c in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#16 0x00007ffff746dbbf in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#17 0x00007ffff7472642 in QWidgetTextControl::processEvent(QEvent*, QMatrix const&, QWidget*) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#18 0x00007ffff746999b in QWidgetTextControl::processEvent(QEvent*, QPointF const&, QWidget*) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#19 0x00007ffff73e4788 in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#20 0x00007ffff72e51d8 in QWidget::event(QEvent*) () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#21 0x00007ffff73e019e in QFrame::event(QEvent*) () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#22 0x00007ffff72a44cc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#23 0x00007ffff72a9e15 in QApplication::notify(QObject*, QEvent*) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#24 0x00007ffff6489663 in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Core.so.5
#25 0x00007ffff72a8aa2 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#26 0x00007ffff72ffbdd in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#27 0x00007ffff7301efb in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#28 0x00007ffff72a44cc in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#29 0x00007ffff72a9630 in QApplication::notify(QObject*, QEvent*) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Widgets.so.5
#30 0x00007ffff6489663 in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Core.so.5
#31 0x00007ffff6a2c44d in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Gui.so.5
---Type <return> to continue, or q <return> to quit---
#32 0x00007ffff6a2de25 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Gui.so.5
#33 0x00007ffff6a12fbf in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Gui.so.5
#34 0x00007fffea67bde0 in ?? () from /home/wont/Desktop/binary_ninja/binaryninja/qt/platforms/../../libQt5XcbQpa.so.5
#35 0x00007ffff4872e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#36 0x00007ffff4873048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#37 0x00007ffff48730ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#38 0x00007ffff64dea87 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Core.so.5
#39 0x00007ffff6487212 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Core.so.5
#40 0x00007ffff648ed3d in QCoreApplication::exec() () from /home/wont/Desktop/binary_ninja/binaryninja/libQt5Core.so.5
#41 0x00000000004254ab in main ()
```

**Comment by wontonSlim** [comment]
Forgot this.
```
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
```

**Comment by plafosse** [comment]
Assuming this is the same crash as #142
